### ISSUE TITLE
GetFeedSubmissionResult returns XML string

### ISSUE THREAD

**Issue by justinemmanuelmercado** [ScaleLeap/amazon-mws-api-sdk#108]
Re: https://github.com/ScaleLeap/amazon-mws-api-sdk/pull/100#discussion_r445363150

**Comment by moltar** [comment]
Maybe we can have a method parameter that defines which format to return?

Example:

```js
getFeedSubmissionResult({
  format: 'xml',
})

// or

getFeedSubmissionResult({
  format: 'json',
})
```

I think this would help users to get the native JS object, and save them from installing a library to convert from XML to JS. As I doubt anyone would be processing XML in JS in any other way than to convert to JSON first.

JSON should probably be the default option too.

What do you think?

**Comment by justinemmanuelmercado** [comment]
Do you think this can be closed now? I get now why you wanted to open this in the first place. I initially thought you wanted to open this issue to make a mental note that the return for this API is different than the rest

**Comment by moltar** [comment]
Ya seems like this is done! ✅
