### ISSUE TITLE
Remove ajv dep

### ISSUE THREAD

**Issue by moltar** [ScaleLeap/amazon-mws-api-sdk#122]
We don't seem to be actually using it, I think.

If not, let's get rid of it then.

Thanks.

**Comment by justinemmanuelmercado** [comment]
Looks like it's being used here https://github.com/ScaleLeap/amazon-mws-api-sdk/blob/6d627b1a3e4b52def89d87eacf9c026c07a97c73/test/unit/parsing.test.ts#L57-L66
