### ISSUE TITLE
(canonicalized as any) - can we avoid any here?

### ISSUE THREAD

**Issue by moltar** [ScaleLeap/amazon-mws-api-sdk#139]
In `test/unit/fulfillment-inbound-shipment.test.ts` -- getting lint warnings. If we can refactor to get rid of `any` - that'd be great, but if we accept is as inevitable, then we should `eslint-ignore` it.

**Comment by justinemmanuelmercado** [comment]
Yeah this can be fixed. This was my bad for assuming that since it's an internal type I didn't need to explicitly define its output. It's one of those long and complicated request objects. I'll get on it :+1:
