### ISSUE TITLE
Try / benchmark other XML parsers

### ISSUE THREAD

**Issue by moltar** [ScaleLeap/amazon-mws-api-sdk#140]
See if there are other XML parser libraries that would be easy to swap without too much change.

If we can do that, then lets try them out and see if we they are faster than the current one.

We can test, for example, by running the test suite 3 times and averaging out the time it took.

**Comment by justinemmanuelmercado** [comment]
Should I close this now or is there another library you had in mind? I've got this list of other libraries that could possibly work but all of them have their own issues

1. https://github.com/segmentio/xml-parser - not updated in 5y
2. https://github.com/assistunion/xml-stream - not updated in 4y
3. https://github.com/libxmljs/libxmljs - does not have xml -> json out of the box
4. https://github.com/rgrove/parse-xml - the output is not a straight XML -> json conversion. It has attributes like `name`, `type` etc. for each tag
5. https://github.com/isaacs/sax-js - this is what `xml2js` uses and it hasn't been updated in 3y

**Comment by moltar** [comment]
None of these libs seems as contenders as they are quite outdated, especially in JS years. But good research none the less. I think with the discovered settings and the #147 PR I see no reason to switch.
