### ISSUE TITLE
Take a second look at the Product type in the Products section

### ISSUE THREAD

**Issue by justinemmanuelmercado** [ScaleLeap/amazon-mws-api-sdk#158]
@moltar I remember not developing the `Product` type because it wasn't completely defined in the Amazon docs, but looking at the C# library, at first glance it looks like it's completely defined though, that may mean that it's possible to define the product based solely on the C# library's code. I'm thinking I'll give it another shot in another PR.

**Comment by moltar** [comment]
Do you have a reference to that? What does it mean "complete defined"? I know that products have different attributes and it is quite dynamic based on a category. And there are thousands of combinations. Defining them all might be a massive task.

**Comment by justinemmanuelmercado** [comment]
> Do you have a reference to that? What does it mean "complete defined"?

Sorry, yeah I definitely didn't mean completely defined as in everything but all of the possible attributes under `Product`. The docs at least define that the type of `Product` used in each request as something like `"Contains two of the sub-elements of the Product element"` which I'm thinking mean that `Product` has these possible sub-elements (the C# library has 7) and each request has the same `Product` but each sub-element available differs request to request.
