### ISSUE TITLE
User agent version should be dynamic

### ISSUE THREAD

**Issue by moltar** [ScaleLeap/amazon-mws-api-sdk#170]
We should read, and extract it from the `package.json` file.

https://github.com/ScaleLeap/amazon-mws-api-sdk/blob/9484296ef72fa86af504d34d0c1f529587a96092/src/http.ts#L389

Be careful though, and make sure to use relative paths. Because the distributed code will end up in `lib/`, while source is in `src/`.

**Comment by justinemmanuelmercado** [comment]
This may be a stupid question, first time I've extracted something from `package.json` to be used in code, but you meant something like this right?

```typescript
import { name, version  } from '../package.json'

//....
   'user-agent': `${name}/${version} (Language=Javascript)`
//...
```

**Comment by moltar** [comment]
This does work in development, but when you go build the project, you'll see that in `lib/` now the folder structure has changed due to `package.json` being included. A better approach would be to read the file using the `fs` built in module. Then parse it with `JSON.parse`.

**Comment by justinemmanuelmercado** [comment]
Ahh alright now I see what you meant, didn't understand it at first. Will check it out
