### ISSUE TITLE
Prefix or suffix all error classes

### ISSUE THREAD

**Issue by moltar** [ScaleLeap/amazon-mws-api-sdk#171]
https://github.com/ScaleLeap/amazon-mws-api-sdk/blob/9484296ef72fa86af504d34d0c1f529587a96092/src/error.ts#L22-L67

I think it would be better to standardize the error class names to something like:

```
ErrClassName
```

Or

```
ClassNameError
```

But I am open to other naming suggestions.

This would help discoverability of them when consuming the library.

We can also export them as a group:

```
export * as Errors from './errors'
```

**Comment by justinemmanuelmercado** [comment]
Sure this sounds good. I prefer this naming scheme`ClassNameError`. I should leave general errors as is right?

**Comment by moltar** [comment]
> I should leave general errors as is right?

What do you mean by that?

**Comment by justinemmanuelmercado** [comment]
```typescript
// General errors
export class InputStreamDisconnected extends HttpError {}
export class InvalidParameterValue extends HttpError {}
export class AccessDenied extends HttpError {}
export class InvalidAccessKeyId extends HttpError {}
export class SignatureDoesNotMatch extends HttpError {}
export class InvalidAddress extends HttpError {}
export class InternalError extends HttpError {}
export class QuotaExceeded extends HttpError {}
export class RequestThrottled extends HttpError {}
```

There are these general errors, do I just leave their names as is?

**Comment by moltar** [comment]
I think they all need an Error suffix?

Any thoughts against that?

**Comment by justinemmanuelmercado** [comment]
Oh I misunderstood what you meant! When you said **ClassNameError** I thought you meant to include the class name where they're from before the error i.e.
`ResourceNotFound` => `EasyShipResourceNotFound`

> I think they all need an Error suffix?

This makes much more sense! 😅

**Comment by moltar** [comment]
:+1: 😁

**Comment by justinemmanuelmercado** [comment]
Closed the wrong issue
