### ISSUE TITLE
Selling Partner API (SP-API) Support

### ISSUE THREAD

**Issue by Stevenje** [ScaleLeap/amazon-mws-api-sdk#234]
Hey Guys, 

Great work on everything, quick question are there plans to switch over to the [Selling Partner API](https://developer.amazonservices.com/) in the near future?

**Comment by moltar** [comment]
No plans to switch as these are different APIs. But I'm considering building a separate package. Maybe codegen from the OpenAPI specs. But I didn't look at it closely yet.

**Comment by Stevenje** [comment]
@moltar That would be great. Do you plan on having a look within the coming weeks? 

Otherwise I'll probably develop my tool using MWS in the interim.

**Comment by ericblade** [comment]
Hello!  Also a MWS library author, thanks for pointing me to this, @Stevenje .  I'll definitely be looking into it, and would love to network with anyone else who's also taking a look.  I like to be at the fore of new things, when possible, so ...

I've just skimmed over the intro pages, and i'm seeing that they're only providing Java and C# libs, so there's definitely a gap there.  Would love to work with some like minded TS/JS devs.

**Comment by moltar** [comment]
@Stevenje don't have a concrete plan yet, but it won't be within a couple of weeks for sure.

**Comment by Stevenje** [comment]
@moltar No worries, thanks for letting me know!
