### ISSUE TITLE
codec decoding issues in finances module

### ISSUE THREAD

**Issue by konradgorski** [ScaleLeap/amazon-mws-api-sdk#243]
Receiving a parse error when querying a record by amazon order id through the `Finances.listFinancialEvents`.

`ParsingError: Problem with the value of property "ListFinancialEventsResponse": Problem with the value of property "ListFinancialEventsResult": Problem with the value of property "FinancialEvents": Problem with the value of property "ShipmentEventList": One of the following problems occured: (0) Problem with the value at index 0: Problem with the value of property "ShipmentItemList": One of the following problems occured: (0) Problem with the value at index 0: Problem with the value of property "ItemChargeList": One of the following problems occured: (0) Problem with the value at index 2: Problem with the value of property "ChargeType": One of the following problems occured: (0) Expected an enum member, but received a string with value "GiftWrap", (1) Expected an undefined, but received a string with value "GiftWrap", (1) Expected an undefined, but received an object with value {{ redacted }} `

**Comment by moltar** [comment]
@konradgorski thank you for the report. It seems to be that the docs are potentially wrong. I have fixed this by changing the case `s/Giftwrap/GiftWrap/`.
