### ISSUE TITLE
codec decoding issues in finances module - ListFinancialEventsResponse

### ISSUE THREAD

**Issue by konradgorski** [ScaleLeap/amazon-mws-api-sdk#251]
Receiving a parse error when querying a record by amazon order id through the Finances.listFinancialEvents.

`ParsingError: Problem with the value of property "ListFinancialEventsResponse": Problem with the value of property "ListFinancialEventsResult": Problem with the value of property "FinancialEvents": Problem with the value of property "AdjustmentEventList": One of the following problems occured: (0) Problem with the value at index 0: Problem with the value of property "AdjustmentType": One of the following problems occured: (0) Expected an enum member, but received a string with value "REVERSAL_REIMBURSEMENT", (1) Expected an undefined, but received a string with value "REVERSAL_REIMBURSEMENT", (1) Expected an undefined, but received an object with value {{ redacted }}`

**Comment by konradgorski** [comment]
[PR-250](https://github.com/ScaleLeap/amazon-mws-api-sdk/pull/250) should resolve this.

**Comment by moltar** [comment]
Thanks @konradgorski! PRs are merged.
