### ISSUE TITLE
Invalid type for numerical ASIN

### ISSUE THREAD

**Issue by mvd7793** [ScaleLeap/amazon-mws-api-sdk#262]
In a similar vein to the past issues, actual ASIN removed:

```
ParsingError: Problem with the value of property "GetMyFeesEstimateResponse": 
Problem with the value of property "GetMyFeesEstimateResult": 
Problem with the value of property "FeesEstimateResultList": 
Problem with the value at index 10: 
Problem with the value of property "FeesEstimateIdentifier": 
Problem with the value of property "IdValue": 
Expected a string, but received a number with value 123456
```

**Comment by mvd7793** [comment]
SellerInputIdentifier on the same object (FeesEstimateIdentifier) also needs to be updated.

I looked at your last PR for a similar issue with `ensureString` and applied the change locally which worked. I can send a PR in the next few days if you don't hit it first. :)

**Comment by moltar** [comment]
@mvd7793 sure, a PR would be appreciated :) Thanks!
