### ISSUE TITLE
Support latest TypeScript features

### ISSUE THREAD

**Issue by gigobyte** [ScaleLeap/amazon-mws-api-sdk#30]
Currently with our tsconfig, we don't support the new operators from TS 3.7 (`?.` and `??`)

```
Details:

    \src\sections\orders.ts:238
            CreatedAfter: parameters.CreatedAfter?.toISOString(),
                                                  ^

    SyntaxError: Unexpected token '.'
```

**Comment by moltar** [comment]
Yeah, I don't think Jest supports this yet. But I am not sure. I have ran into this before myself, and I just didn't use that feature yet.

Do you know how to solve this?

**Comment by gigobyte** [comment]
https://github.com/kulshekhar/ts-jest/issues/1405

> I think it was my tsconfig target being es2020, had to drop down to es2019.

Could be this.

**Comment by moltar** [comment]
@gigobyte do you want to try this fix?

**Comment by gigobyte** [comment]
@moltar The problem is that `@scaleleap/utils` is not visible to me and the tsconfig is there, that's why I made this issue.

**Comment by moltar** [comment]
Not sure what it has to do with `@scaleleap/utils` though?

**Comment by gigobyte** [comment]
This is not a jest issue, but a TS issue:
https://stackoverflow.com/questions/58725711/how-to-get-optional-chaining-working-in-typescript
https://github.com/kulshekhar/ts-jest/issues/1283#issuecomment-572412196

**Comment by moltar** [comment]
But we can override the target, right? Just change the `tsconfig` and set it to `2020` if that is what works.

**Comment by gigobyte** [comment]
Sure, just figured you might want to do that for all projects. I'll make a PR in a minute.

**Comment by moltar** [comment]
> Sure, just figured you might want to do that for all projects. I'll make a PR in a minute.

I might, if it works.

But I am not the author of the `tsconfigs` package, so I can't really alter that universally.

But if this does work, I'll raise an issue there.
