### ISSUE TITLE
ListOrdersByNextToken only needs NextToken as a parameter

### ISSUE THREAD

**Issue by justinemmanuelmercado** [ScaleLeap/amazon-mws-api-sdk#40]
https://github.com/ScaleLeap/amazon-mws-api-sdk/blob/e1fd605b8ebd6d647ff32f61bf4c0e67aafdf62e/src/sections/orders.ts#L341-L353

`ListOrdersByNextToken` is attaching too many parameters but MWS docs only lists NextToken as parameter

http://docs.developer.amazonservices.com/en_CA/orders-2013-09-01/Orders_ListOrdersByNextToken.html

**Comment by gigobyte** [comment]
You are correct, we don't need those params. Feel free to remove the argument and the `...spread` in the request.
