### ISSUE TITLE
I am having trouble getting the examples working

### ISSUE THREAD

**Issue by IonicaBizau** [ScaleLeap/amazon-mws-api-sdk#411]
First of all, thank you for the wonderful library! ✨ 

However, I am trouble getting the authentication working.

Here is my current code:

```js
const {
  amazonMarketplaces,
  HttpClient,
  Sellers,
  Orders,
  Products,
  MWS
} = require('@scaleleap/amazon-mws-api-sdk')

const mwsOptions = {
  marketplace: amazonMarketplaces.US,
  awsAccessKeyId: "...",
  mwsAuthToken: "...",
  sellerId: "...",
  secretKey: "...",
}

// Using MWS client
const main = async () => {
  const http = new HttpClient(mwsOptions)
  const mws = new MWS(http)

  /**
   * Get status for Sellers API
   */
  const [serviceStatus] = await mws.sellers.getServiceStatus()
  if (serviceStatus.Status === 'GREEN') {
    console.log(`Sellers API is up on ${serviceStatus.Timestamp}!`)
  }


debugger
    const products = new Products(http)
    const marketplace = amazonMarketplaces.US
    const [response, meta] = await products.getMatchingProduct({
        MarketplaceId: marketplace.id,
        ASINList: ['B0946YBLPV'],
    })
   debugger
}

main();
```

I have been added as admin to an Amazon account and I have access to the developer dashboard and have created a security profile.

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/2864371/126753837-ffdb3696-e1db-4b92-865a-14aaa1b89540.png">

I used the credentials above for the `sellerId` and `secretKey`. I have a hard time understanding what `awsAccessKeyId` and `mwsAuthToken` should actually be... I tried using keys from an IAM user, but I am getting the following error:

```
< (node:782968) UnhandledPromiseRejectionWarning: SignatureDoesNotMatchError: GetMatchingProduct request failed
<     at HttpClient.request (/.../node_modules/@scaleleap/amazon-mws-api-sdk/lib/http.js:253:44)
<     at process._tickCallback (internal/process/next_tick.js:68:7)
```

How can I get the authentication work?

Thank you!

**Comment by moltar** [comment]
This package is for MWS API (http://docs.developer.amazonservices.com/en_US/dev_guide/index.html).

Your screenshot shows an Amazon Developer console, which leads me to believe you are not using MWS.

Amazon Developer console at best can provide Amazon Advertising API credentials, but even then, you'd need to OAuth first, to get the tokens, before using them.

**Comment by IonicaBizau** [comment]
@moltar Thanks for the quick reply! Is there any way to automate this and not need the OAuth steps, but instead getting some never-expiring tokens and set up the server script?

I asked this StackOverflow question and perhaps I haven't got the best answer: https://stackoverflow.com/q/68251611/1420197

**Comment by moltar** [comment]
MWS API does not use OAuth.

Selling Partner API (for which we also have an SDK) uses OAuth, and you can self-authorize via the Amazon Seller Central Developer account.

**Comment by moltar** [comment]
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#self-authorization

**Comment by IonicaBizau** [comment]
So, if we would like to use the MWS, where should we get the credentials from?

**Comment by moltar** [comment]
I posted the docs link. Please go thru that.

Also I wouldn't build anything new on MWS as it's deprecated.

**Comment by IonicaBizau** [comment]
@moltar Thank you! I will talk to the admins to sign up for the Selling Partner API and eventually will open issues in the other repository. Keep up the great work! ❇️
