### ISSUE TITLE
cleanParameters does not work for product.GetMyFeesEstimate

### ISSUE THREAD

**Issue by justinemmanuelmercado** [ScaleLeap/amazon-mws-api-sdk#46]
clean parameters currently only works for strings and array of strings but [GetMyFeesEstimate's parameters](http://docs.developer.amazonservices.com/en_CA/products/Products_GetMyFeesEstimate.html) consist of a list of [FeesEstimateRequest](http://docs.developer.amazonservices.com/en_CA/products/Products_Datatypes.html#FeesEstimateRequest). 

I can modify how parameters are cleaned to accomodate this type of parameter but just putting this out here just in case anyone wants to chime in

**Comment by justinemmanuelmercado** [comment]
Also shouldn't this https://github.com/ScaleLeap/amazon-mws-api-sdk/blob/93479071112dd7beba069ca13e81eee93f8e4257/src/http.ts#L143

be 

```javascript
 Object.assign(result, { [`${k}.${index + 1}`]: String(v[index]) }) 
```

Because as of now, currently running

```javascript
{
    abc: ["a", "b", "c"]
}
```

through `cleanParameters` yields

```json
{ "abc.1": "a,b,c", "abc.2": "a,b,c", "abc.3": "a,b,c" }
```

instead of what I think should be

```json
{ "abc.1": "a", "abc.2": "b", "abc.3": "c" }
```

@gigobyte Sorry if I'm misunderstanding anything

**Comment by moltar** [comment]
>  Object.assign(result, { [`${k}.${index + 1}`]: String(v[index]) }) 

Yes, this is right!

Please do a fix of this and create a test for that.
