### ISSUE TITLE
Inconsistencies with what's in Amazon's docs with their sample responses

### ISSUE THREAD

**Issue by justinemmanuelmercado** [ScaleLeap/amazon-mws-api-sdk#49]
For example

In docs the name of the prop is `IncludedFeeDetailList`

<img width="1003" alt="Screen Shot 2020-05-21 at 10 25 09 PM" src="https://user-images.githubusercontent.com/15125483/82568936-1fe7f280-9bb2-11ea-9e26-215ca098b2c0.png">

But the examples have it as just `IncludedFeeList`

[IncludedFeeList in "Example response (Success)"](http://docs.developer.amazonservices.com/en_CA/products/Products_GetMyFeesEstimate.html)

<img width="405" alt="Screen Shot 2020-05-21 at 10 30 30 PM" src="https://user-images.githubusercontent.com/15125483/82569356-b61c1880-9bb2-11ea-81fe-69117fbc40b2.png">

There were 2 other examples I found, 1 is in the `Points` type, they have `PointsMonetaryValue` as required but in the XML sample in the docs, it's omitted, and I forgot to document the other one.

[Type Points](http://docs.developer.amazonservices.com/en_CA/products/Products_Datatypes.html#Points)

<img width="357" alt="Screen Shot 2020-05-21 at 10 34 39 PM" src="https://user-images.githubusercontent.com/15125483/82569826-54a87980-9bb3-11ea-802a-cd71916cea02.png">

**Comment by justinemmanuelmercado** [comment]
@moltar My question is how should I approach this? Build around the XML or the docs

**Comment by moltar** [comment]
Did you check how other libraries are handling this?

**Comment by justinemmanuelmercado** [comment]
Ooh that's a good a point, I should've thought of that earlier. Thanks!
