### ISSUE TITLE
Add interface to require only one of two (or more) properties to exist

### ISSUE THREAD

**Issue by justinemmanuelmercado** [ScaleLeap/amazon-mws-api-sdk#68]
http://docs.developer.amazonservices.com/en_CA/fba_inventory/FBAInventory_ListInventorySupply.html

APIs like above have a clause in their parameters like 

```
Yes, if QueryStartDateTime is not specified.

Specifying both QueryStartDateTime and SellerSkus returns an error. 
```
there's another API with the same parameter requirement but I forgot which. Will need to review docs of currently implemented APIs

 Small change but still a DX improvement

**Comment by justinemmanuelmercado** [comment]
relevant: https://stackoverflow.com/questions/40510611/typescript-interface-require-one-of-two-properties-to-exist

**Comment by moltar** [comment]
Yeah, good call!
