### ISSUE TITLE
Abstract HttpClient creation into a factory function

### ISSUE THREAD

**Issue by moltar** [ScaleLeap/amazon-mws-api-sdk#76]
The following code is repeated in every integration test:

https://github.com/ScaleLeap/amazon-mws-api-sdk/blob/a4d27a3e44e01a9dd05571ec04d4bb03265592eb/test/integration/orders.test.ts#L7-L15

We should probably just have it abstracted into a function into a separate file.

**Comment by justinemmanuelmercado** [comment]
Good point, will fit it in
