### ISSUE TITLE
Expose all parameter types

### ISSUE THREAD

**Issue by moltar** [ScaleLeap/amazon-mws-api-sdk#96]
I think it'd be useful to expose the method parameter types, so that parameters can be build outside of the method call and be typed.

E.g. I am creating a subscription and then subscribing to it. There are the same parameters, but they need to be repeated:

https://github.com/ScaleLeap/amazon-mws-api-sdk/blob/a1e5c8b1f33a7ed7a159a0dcdb1a92b4ecf3720e/test/integration/subscriptions.test.ts#L26

If you try to abstract that into an object, you'll get type errors stating that:

> Type 'string' is not assignable to type '"SQS"'.

---

Screenshot:

<img width="707" alt="image" src="https://user-images.githubusercontent.com/491247/85265163-07fadb80-b49c-11ea-98d0-73c44f16ba0e.png">

---

```
Type '{ AttributeList: { Key: string; Value: string; }[]; DeliveryChannel: string; }' is not assignable to type 'Destination'.
  Types of property 'DeliveryChannel' are incompatible.
    Type 'string' is not assignable to type '"SQS"'.ts(2322)
```

But also, regardless of errors, I think it'd be useful to do something like:

```ts
const dest: Destination = {
 // and this be type checked / intellisensed
}
```

**Comment by justinemmanuelmercado** [comment]
They're exported here.

https://github.com/ScaleLeap/amazon-mws-api-sdk/blob/a1e5c8b1f33a7ed7a159a0dcdb1a92b4ecf3720e/src/sections/subscriptions.ts#L13-L20

But you may be referring to exposing them another way. Let me know if you think there's a better way to expose them to be usable for the users

**Comment by moltar** [comment]
Ah, yeah, missed that part. Certainly useful.

But I was thinking more like the whole parameter interface and all of the underlying parts need to be exposed.

Like in my example, if I just want to have a destination hard coded somewhere once, and it be type checked, it is not currently possible.

**Comment by justinemmanuelmercado** [comment]
Ahh so you mean exposing something like `export interface Destination {...}`?

**Comment by justinemmanuelmercado** [comment]
I can push something like that, have you review it and if approved I'll create the issue to apply it to other sections where it could be a useful change

**Comment by moltar** [comment]
> Ahh so you mean exposing something like `export interface Destination {...}`?

Ya for all method parameter interfaces, even the inner ones, where makes sense.
